import type { Metadata } from 'next'
import {Inter, Poppins } from 'next/font/google'
import './globals.css'

const inter = Poppins({ subsets: ['latin'], weight: ['100', '200', '300','400','500','600', '700', '800', '900'] })


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`relative h-full antialiased overflow-x-hidden ${inter.className}`}>{children}</body>
    </html>
  )
}
